version: '2'
services:
    front-docker:
        container_name: "frontend"
        image: ghcr.io/violet-evergardenz/int222-frontend:latest
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - /home/bluzeadmin/front-end/nginx/data/.well-known/pki-validation:/usr/share/nginx/html/.well-known/pki-validation/
            - /home/bluzeadmin/front-end/nginx:/var/log/nginx/
            - /home/bluzeadmin/front-end/nginx/ssl:/ssl/
        restart: on-failure