version: '2'
services:
    front-docker:
        build: .
        image: front-docker
        ports:
            - "8080:8080"
networks:
        default:
            external:
                name: circlenet