version: '2'
services:
    front-docker:
        container_name: "frontend"
        image: ghcr.io/violet-evergardenz/int222-frontend:latest
        ports:
            - "8080:8080"
        restart: on-failure
        networks:
            project2-net:
                ipv4_address: 172.21.0.2
networks:
    default:
        external:
            name: project2-net
    project2-net:
        external: true
        